[package]
name = "const_regex_regex_transformer"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
itertools = "0.14.0"
either = "1.13.0"
derive-getters = "0.5.0"
const_regex_util = { path="../const_regex_util" }
